substitutions:
  name: "exit-poll"
  friendly_name: "Exit Poll"
  led_chip: "WS2812"
  led_order: "GRB"
  display_model: "ILI9488"

packages:
  exit-poll:
    url: https://github.com/romkey/pdxhackerspace-exit-poll
    files: [esphome/exit-poll.yml, esphome/tinys3.yml]
    ref: main
    refresh: 1s

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: w.x.y.z

  ap:
    ssid: "PDX Hackerspace Exit Poll Fallback Hotspot"
    password: "YOUR HOTSPOT PASSWORD"
