substitutions:
  name: "exit-poll"
  friendly_name: "Exit Poll"
  led_chip: "WS2812"
  led_order: "GRB"
  led_number: "8"
  display_model: "ILI9488_A"

api:
  encryption:
    key: !secret homeassistant_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: w.x.y.z
  ap: 
    ssid: "Test"
    password: "ctrlctrlh"

packages:
  tinys3: !include tinys3.yml
  exit-poll: !include exit-poll.yml
